class Skills:
    def __init__(self, data):
        self.id = data.get('ID')
        self.name = data.get('Name')
        self.barbarian = data.get('Barbarian')
        self.bard = data.get('Bard')
        self.cleric = data.get('Cleric')
        self.druid = data.get('Druid')
        self.fighter = data.get('Fighter')
        self.monk = data.get('Monk')
        self.paladin = data.get('Paladin')
        self.ranger = data.get('Ranger')
        self.rogue = data.get('Rogue')
        self.sorcerer = data.get('Sorcerer')
        self.wizard = data.get('Wizard')
        self.untrained = data.get('Untrained')
        self.armor_check_penalty = data.get('Armor_Check_Penalty')
        self.key_ability = data.get('Key_Ability')
