class Spells:
    def __init__(self, data):
        self.id = data.get('ID')
        self.name = data.get('Name')
        self.school = data.get('School')
        self.casting_time = data.get('Casting Time')
        self.components = data.get('Components')
        self.range = data.get('Range')
        self.effect = data.get('Effect')
        self.target = data.get('Target')
        self.area = data.get('Area')
        self.duration = data.get('Duration')
        self.saving_throw = data.get('Saving Throw')
        self.spell_resistance = data.get('Spell Resistance')
        self.description = data.get('Description')
        self.bard = data.get('Bard')
        self.cleric = data.get('Cleric')
        self.druid = data.get('Druid')
        self.paladin = data.get('Paladin')
        self.ranger = data.get('Ranger')
        self.sorc_wiz = data.get('SorcWiz')
